name: Compile LaTeX files

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: compile
        run: devenv shell build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv_english.pdf
            cv_portuguese.pdf
          tag_name: latest
